// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ServeRootPageGet Serve Root Page
	// (GET /)
	ServeRootPageGet(w http.ResponseWriter, r *http.Request)
	// LoginApiLoginPost Login
	// (POST /api/login)
	LoginApiLoginPost(w http.ResponseWriter, r *http.Request)
	// LogoutApiLogoutGet Logout
	// (GET /api/logout)
	LogoutApiLogoutGet(w http.ResponseWriter, r *http.Request)
	// RegisterApiRegisterPost Register
	// (POST /api/register)
	RegisterApiRegisterPost(w http.ResponseWriter, r *http.Request)
	// SearchApiSearchGet Search
	// (GET /api/search)
	SearchApiSearchGet(w http.ResponseWriter, r *http.Request, params SearchApiSearchGetParams)
	// WeatherApiWeatherGet Weather
	// (GET /api/weather)
	WeatherApiWeatherGet(w http.ResponseWriter, r *http.Request)
	// ServeLoginPageLoginGet Serve Login Page
	// (GET /login)
	ServeLoginPageLoginGet(w http.ResponseWriter, r *http.Request)
	// ServeRegisterPageRegisterGet Serve Register Page
	// (GET /register)
	ServeRegisterPageRegisterGet(w http.ResponseWriter, r *http.Request)
	// ServeWeatherPageWeatherGet Serve Weather Page
	// (GET /weather)
	ServeWeatherPageWeatherGet(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ServeRootPageGet Serve Root Page
// (GET /)
func (_ Unimplemented) ServeRootPageGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LoginApiLoginPost Login
// (POST /api/login)
func (_ Unimplemented) LoginApiLoginPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutApiLogoutGet Logout
// (GET /api/logout)
func (_ Unimplemented) LogoutApiLogoutGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterApiRegisterPost Register
// (POST /api/register)
func (_ Unimplemented) RegisterApiRegisterPost(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SearchApiSearchGet Search
// (GET /api/search)
func (_ Unimplemented) SearchApiSearchGet(w http.ResponseWriter, r *http.Request, params SearchApiSearchGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// WeatherApiWeatherGet Weather
// (GET /api/weather)
func (_ Unimplemented) WeatherApiWeatherGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServeLoginPageLoginGet Serve Login Page
// (GET /login)
func (_ Unimplemented) ServeLoginPageLoginGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServeRegisterPageRegisterGet Serve Register Page
// (GET /register)
func (_ Unimplemented) ServeRegisterPageRegisterGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServeWeatherPageWeatherGet Serve Weather Page
// (GET /weather)
func (_ Unimplemented) ServeWeatherPageWeatherGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ServeRootPageGet operation middleware
func (siw *ServerInterfaceWrapper) ServeRootPageGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeRootPageGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginApiLoginPost operation middleware
func (siw *ServerInterfaceWrapper) LoginApiLoginPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginApiLoginPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutApiLogoutGet operation middleware
func (siw *ServerInterfaceWrapper) LogoutApiLogoutGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutApiLogoutGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterApiRegisterPost operation middleware
func (siw *ServerInterfaceWrapper) RegisterApiRegisterPost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterApiRegisterPost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchApiSearchGet operation middleware
func (siw *ServerInterfaceWrapper) SearchApiSearchGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchApiSearchGetParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "language"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchApiSearchGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// WeatherApiWeatherGet operation middleware
func (siw *ServerInterfaceWrapper) WeatherApiWeatherGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WeatherApiWeatherGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServeLoginPageLoginGet operation middleware
func (siw *ServerInterfaceWrapper) ServeLoginPageLoginGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeLoginPageLoginGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServeRegisterPageRegisterGet operation middleware
func (siw *ServerInterfaceWrapper) ServeRegisterPageRegisterGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeRegisterPageRegisterGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServeWeatherPageWeatherGet operation middleware
func (siw *ServerInterfaceWrapper) ServeWeatherPageWeatherGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeWeatherPageWeatherGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.ServeRootPageGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/weather", wrapper.ServeWeatherPageWeatherGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/register", wrapper.ServeRegisterPageRegisterGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/login", wrapper.ServeLoginPageLoginGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/search", wrapper.SearchApiSearchGet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/weather", wrapper.WeatherApiWeatherGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/register", wrapper.RegisterApiRegisterPost)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/login", wrapper.LoginApiLoginPost)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/logout", wrapper.LogoutApiLogoutGet)
	})

	return r
}
